testthat::test_that("simulador preserva lotes e produz CSV compativel com o painel", {
  destino <- tempfile("p1-dados-")
  on.exit(unlink(destino, recursive = TRUE), add = TRUE)
  script <- file.path(raiz_teste, "simulador", "gerar_dados.R")
  executar <- function(n = 25) system2(file.path(R.home("bin"), "Rscript"),
    shQuote(c(script, destino, as.character(n), "42")), stdout = TRUE, stderr = TRUE)
  primeiro <- executar()
  testthat::expect_null(attr(primeiro, "status"))
  arquivo <- list.files(destino, "vendas[.]csv$", recursive = TRUE, full.names = TRUE)
  hash <- tools::md5sum(arquivo)
  segundo <- executar()
  testthat::expect_null(attr(segundo, "status"))
  arquivos <- list.files(destino, "vendas[.]csv$", recursive = TRUE, full.names = TRUE)
  testthat::expect_length(arquivos, 2)
  testthat::expect_identical(tools::md5sum(arquivo), hash)
  dados <- lapply(arquivos, ler_vendas)
  testthat::expect_true(all(vapply(dados, nrow, integer(1)) == 25))
  testthat::expect_equal(nrow(tratar_vendas(dados[[1]])$dados), 25)
  testthat::expect_false(identical(dados[[1]][["ID Execucao"]][1], dados[[2]][["ID Execucao"]][1]))
  testthat::expect_identical(dados[[1]][colunas_vendas], dados[[2]][colunas_vendas])
  invalido <- suppressWarnings(executar(9))
  testthat::expect_equal(attr(invalido, "status"), 1)
  testthat::expect_length(list.files(destino, "vendas[.]csv$", recursive = TRUE), 2)
  destino_arquivo <- tempfile("p1-nao-diretorio-")
  writeLines("preservar", destino_arquivo)
  on.exit(unlink(destino_arquivo), add = TRUE)
  invalido <- suppressWarnings(system2(file.path(R.home("bin"), "Rscript"),
    shQuote(c(script, destino_arquivo, "25", "42")), stdout = TRUE, stderr = TRUE))
  testthat::expect_equal(attr(invalido, "status"), 1)
  testthat::expect_identical(readLines(destino_arquivo), "preservar")
})
